name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Make jest executable
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        run: npm test

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app || git clone https://github.com/akshaykashyapgithub/node-ci-cd-pipeline-git-actions.git /home/ec2-user/app
            cd /home/ec2-user/app
            git pull origin main
            docker stop nodeapp-cicd-container || true
            docker rm nodeapp-cicd-container || true
            docker build -t nodeapp-cicd-image:latest .
            docker run -d --name nodeapp-cicd-container -p 80:3000 nodeapp-cicd-image:latest
